language: c

install:
  - sudo add-apt-repository ppa:avsm/ocaml41+opam11 -y
  - sudo apt-get update -q
  - sudo apt-get install ocaml ocaml-native-compilers camlp4-extra opam
  - npm install

script:
  - grunt