language: c

install:
  - echo "yes" | sudo add-apt-repository ppa:$ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq ocaml ocaml-native-compilers camlp4-extra opam
  - npm install

script:
  - grunt